### PR TITLE
set correct solr_filename for Solr 4.0.0

### PR DESCRIPTION
**Pull request by pmb59**
While trying to install Solr 4.0.0 I notice the role was trying to download `solr-4.0.0.tgz` instead of the correct one `apache-solr-4.0.0.tgz` here https://archive.apache.org/dist/lucene/solr/4.0.0/. These edits should fix this.

Thank you for writing this very useful Ansible role.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Ha! Who would've thought they used that old format for 4.0.0 then changed it for follow-up versions? I'll merge if tests continue passing. Thanks.

**Comment by geerlingguy** [comment]
Looks like yamllint is finding some extra spaces in your changes.

**Comment by geerlingguy** [comment]
There's still a trailing space hiding out somewhere :(

**Comment by pmb59** [comment]
I've run yamllint locally and after the latest commit there are no more trailing spaces. However is reports an error in L24
```
$ yamllint -f github main.yml
::error file=main.yaml,line=24,col=81::[line-length] line too long (83 > 80 characters)
```
but I assume the line-length configuration here is different as this line wasn't edited.

**Comment by pmb59** [comment]
@geerlingguy It passed the linting but now it seems to be a problem with the Molecule tests

**Pull request closed without merging**
