### PR TITLE
Add molecule, fix idempotence, bad syntax (using registers instead of notifications)

### PR DESCRIPTION
**Pull request by grzegorznowak**
all this mostly to add molecule and a draft of unit tests.
I require molecule in all my roles and some of them (depending on this role) weren't passing due to molecule errors/warning.
Highly recommend adding it to your other roles, as it's quite kick ass. Let me know if you need help implementing, I can cover some of those @geerlingguy

### CODE REVIEW

**Comment by geerlingguy** [comment]
This is a looooot of new code. If there are problems like bad syntax or idempotence issues, I'd rather those be in PRs addressing each issue individually.

As I maintain over 100 roles, I don't currently use molecule, and would not start using it unless I started using it across all 100 roles I maintain.

**Comment by grzegorznowak** [comment]
There isn't any new code per-se, it's just a rewrite to meet the ansible-lint requirements mostly.
And neither I  have time to issue 5 separate PRs.
Quite a bummer man, especially since I've offered you help to make your roles even more rock solid.

**Comment by geerlingguy** [comment]
@grzegorznowak - Thank you for giving back, it's definitely appreciated since most people wouldn't take the time. But I don't want to make a major architectural shift for just one role out of hundreds (especially a role that is critical to many pieces of my own managed infrastructure) when the automated tests currently in place are (and have been) working fine for years.

I do see value in possibly switching to molecule someday, but at this point it's more overhead and for minimal (if any) value gain.

Additionally, there are a _lot_ of default ansible-lint things (like using `True` instead of `yes` in all circumstances) that I disagree with and would not want to accept regardless. It seems to be awfully picky out of the box compared to linters for other languages I use.

Finally, there's no way I can justify spending a few hours reviewing this large set of changes when I often have one hour or less in a given day (sometimes a week) to spread across all my open source projects. Please see https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes for more information.

**Comment by grzegorznowak** [comment]
Sure I understand all that, being on the same tight time constraint daily. The only problem I see with that approach, and I see it regularly, is - refusing spending time on QA, testing and linting results in even more time wasted later on. 
If anything this might be an indication of needing to circumvent your current involvement in the set of OS project you have and distribute across trusty contributors. Why would you want to stall on improving when there is a neat tool that is only waiting to be incorporated. 
Believe me that the idempotence test molecure provides is THE one that will give you happy days.
Cheers

**Comment by geerlingguy** [comment]
This role already has a stable and trusted idempotence test built in... what I'm saying is that moving to Molecule would provide the exact same feature set my current testing platform already has, but would make this role different than all the others (and all the other playbooks) I maintain.

I am extremely thorough in testing, QA, etc., and believe me, if I weren't, I could not maintain the 200+ projects I do on GitHub publicly, nor the 100+ more I do so in private repos :)

**Comment by geerlingguy** [comment]
Also, I have no qualms about letting people fork my work; I strongly encourage it, and that's why I stick to the MIT license. I build these roles for myself, and I'm my #1 customer! If someone wants something different, it's usually extensible, but it's also easy enough to fork (there's a button for it in the top right of every page ;) ).

**Comment by grzegorznowak** [comment]
Thanks for the response.
Yes, I'm now looking at the /tests folder there, and correct me if I'm wrong, but it's impossible for one to run any test suite locally atm ?
Moreover some test playbooks for different versions of solr, that travis consumes, have bespoke configuration (namely 7.x and 8.x). Could you elaborate on why is that or does it have to be reflected when actually setting up the role for a given server ? 

I still don't think CI can or should be replacing proper units people can run locally at their will.

**Comment by geerlingguy** [comment]
@grzegorznowak - You can run all the tests locally, identically to how they're run in Travis CI, by following the README directions in the `tests` folder.

And yes, the tests are different for different versions, because Solr has seen some radical differences in both dependencies, how they're installed, and how they work from versions 3-4-5-6-7 (mostly in 3-4 and 5-6 though). This role supports them all :)

**Pull request closed without merging**
